### PR TITLE
Update the bug tracker advice to de-emphasize rt.cpan.org

### PR DESCRIPTION
**Pull request by briandfoy**

### CODE REVIEW

**Comment by briandfoy** [comment]
What needs to happen for this to move forward?

**Comment by briandfoy** [comment]
This PR has been approved. What needs to happen for it to be merged?

**Comment by karenetheridge** [comment]
I need to have the time to review it and the others in the queue, which is usually only on weekends.

**Comment by briandfoy** [comment]
Here are the patch files in case the PR disappears when I delete my fork.

[0001-Update-the-bugtracker-advice.patch](https://github.com/perl-doc-cats/perlfaq/files/12862147/0001-Update-the-bugtracker-advice.patch)
[0002-Edit-the-bugtracker-answer.patch](https://github.com/perl-doc-cats/perlfaq/files/12862148/0002-Edit-the-bugtracker-answer.patch)

**Pull request merged**
